name: Release workflow

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      PROJECT:
        required: true
        type: string
      DOTNET_IMAGE:
        required: true
        type: string
      PROJECT_NAME_COMMIT_SUFFIX:
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/test-common.yml
    with:
      DOTNET_IMAGE: ${{ inputs.DOTNET_IMAGE }}
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
  publish-new-version:
    needs: [ test ]
    uses: ./.github/workflows/publish-new-version-common.yml
    with:
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
      PROJECT_NAME_COMMIT_SUFFIX: ${{ inputs.PROJECT_NAME_COMMIT_SUFFIX }}
  release:
    needs: [ test, publish-new-version ]
    if: needs.publish-new-version.outputs.OUTCOME == 'success'
    uses: ./.github/workflows/release-nuget-common.yml
    with:
      DOTNET_IMAGE: ${{ inputs.DOTNET_IMAGE }}
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
      PROJECT: ${{ inputs.PROJECT }}
    secrets: inherit
