name: Release prometheus workflow

on:
  push:
    branches:
      - main
      - release/**
    paths:
      - Zupit.Prometheus/**
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/common-release.yml
    with:
      DOTNET_IMAGE: 'mcr.microsoft.com/dotnet/sdk:8.0.101-alpine3.18-amd64'
      WORKING_DIRECTORY: Zupit.Prometheus
      PROJECT: Zupit.Prometheus
      PROJECT_NAME_COMMIT_SUFFIX: Prometheus
    secrets: inherit
