name: Release common workflow

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      PROJECT:
        required: true
        type: string
      DOTNET_IMAGE:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.DOTNET_IMAGE }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: dotnet test

      - name: Create NuGet package
        run: dotnet pack -c Release -o ./artifacts/${{ inputs.PROJECT }} ${{ inputs.PROJECT }}

      - name: Publish NuGet package
        run: dotnet nuget push ./artifacts/${{ inputs.PROJECT }}/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.ZUPIT_NUGET_TOKEN }}
