name: Test common workflow

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      DOTNET_IMAGE:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.DOTNET_IMAGE }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: dotnet test